PARSER = ../C/parser

test: test1 test2 test3 test4 test5 test6 test7 test8

test1:
	$(PARSER) < test1.in | diff test1.out -

test2:
	$(PARSER) < test2.in | diff test2.out -

test3:
	$(PARSER) < test3.in | diff test3.out -

test4:
	$(PARSER) < test4.in | diff test4.out -

test5:
	$(PARSER) < test5.in | diff test5.out -

test6:
	$(PARSER) < test6.in | diff test6.out -

test7:
	$(PARSER) < test7.in | diff test7.out -

test8:
	$(PARSER) < test8.in | diff test8.out -